name: Static analysis

on:
  # 'pull_request_target' allows this Action to also run on forked repositories
  # The output will be shown in PR comments (unless the 'force_console_print' flag is used)
  pull_request_target:
    branches:
      - "*"

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5

    - name: Run static analysis
      uses: esp-cpp/StaticAnalysis@master
      with:
        # Do not build the project and do not use cmake to generate compile_commands.json
        use_cmake: false

        # (Optional) cppcheck args
        cppcheck_args: --check-level=exhaustive --force --enable=all --inline-suppr --inconclusive --platform=mips32 --std=c++17 --suppressions-list=$GITHUB_WORKSPACE/suppressions.txt
